export const SELECT_MOLECULE_SIDE_MENU = 'SELECT_MOLECULE_SIDE_MENU';
export const DISPLAY_MOLECULE = 'DISPLAY_MOLECULE';
export const ACTIVATE_MOLECULE_AREA = 'ACTIVATE_MOLECULE_AREA';
export const DEACTIVATE_MOLECULE_AREA = 'DEACTIVATE_MOLECULE_AREA';
export const PREPARE_MOLECULE_AREA_FOR_DELETION =
  'PREPARE_MOLECULE_AREA_FOR_DELETION';
export const REMOVE_MOLECULE_AREA_DELETION = 'REMOVE_MOLECULE_AREA_DELETION';
export const CLEAR_MOLECULE_AREA = 'CLEAR_MOLECULE_AREA';
export const TOGGLE_SPECTRUM = 'TOGGLE_SPECTRUM';
